require "eater_scraper/version"
require "nokogiri"
require "open-uri"
require "colorize"
require_relative "Scraper.rb"
require_relative "Article.rb"
require_relative "City.rb"
require_relative "CLI_Controller.rb"
